// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("WebApplication1.Models.Produce", b =>
                {
                    b.Property<int>("ProduceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProduceID");

                    b.ToTable("Produces");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            Description = "Oranges"
                        },
                        new
                        {
                            ProduceID = 2,
                            Description = "Apples"
                        },
                        new
                        {
                            ProduceID = 3,
                            Description = "Peaches"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.ProduceSupplier", b =>
                {
                    b.Property<int>("ProduceID")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("SupplierID")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProduceID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProduceSuppliers");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            SupplierID = 1,
                            Qty = 25
                        },
                        new
                        {
                            ProduceID = 2,
                            SupplierID = 2,
                            Qty = 12
                        },
                        new
                        {
                            ProduceID = 3,
                            SupplierID = 1,
                            Qty = 30
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            SupplierName = "Kin's Market"
                        },
                        new
                        {
                            SupplierID = 2,
                            SupplierName = "Fresh Street Market"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.ProduceSupplier", b =>
                {
                    b.HasOne("WebApplication1.Models.Produce", "Produce")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("ProduceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Supplier", "Supplier")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produce");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebApplication1.Models.Produce", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });

            modelBuilder.Entity("WebApplication1.Models.Supplier", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
